version: '3.4'

services:
  customersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  customersmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

